### PR TITLE
Cleanup deprecation

### PR DESCRIPTION
**Pull request by timja**
I based the Step deprecation fixes off:
https://github.com/jenkinsci/office-365-connector-plugin/blob/master/src/main/java/jenkins/plugins/office365connector/workflow/StepParameters.java

Seems better now

### CODE REVIEW

**Comment by casz** [comment]
@timja compilation error 😇
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fslack-plugin/detail/PR-491/1/pipeline#step-39-log-70

**Comment by timja** [comment]
Oops, will need some time to figure out how to mock the stepcontext or a more appropriate way of performing the tests

**Comment by casz** [comment]
@timja take a look at office365 plugin 😂

**Comment by timja** [comment]
It has 1 test there for configRoundTrip 😉 
Already looked there 👅

**Comment by casz** [comment]
@timja github search to the rescue: https://github.com/search?q=org%3Ajenkinsci+path%3Asrc%2Ftest+listener+step&unscoped_q=path%3Asrc%2Ftest+listener+step

**Comment by timja** [comment]
I checked 2 of them and they are both using the deprecated guice injection method still
https://github.com/jenkinsci/contrast-continuous-application-security-plugin/blob/b608473420f686661cdd81db8d493f2e37cb7011/src/main/java/com/aspectsecurity/contrast/contrastjenkins/VulnerabilityTrendStep.java#L216
and I checked the Mattermost one.

I could assign the var in the constructor but then I would need to throw some new exceptions out...

I'll have a look later on unless you can see a more modernised one that does this

**Comment by timja** [comment]
Thanks exactly what I was looking for

**Comment by casz** [comment]
You are so very welcome 🎉

**Pull request merged**
