### PR TITLE
Send only one message with commit list.

### PR DESCRIPTION
**Pull request by kenji21**

### CODE REVIEW

**Comment by kenji21** [comment]
Just rebased current upstream/master (my fork was 4 commits behind)

**Comment by NikitaGl** [comment]
Sorry, is there any docs for using this functionality?

**Comment by timja** [comment]
Its not opt in, everyone gets it, previously 2 messages were sent, now there's only one message

**Comment by NikitaGl** [comment]
I've found the implementation for freestyle jobs, but how to do add this in pipeline?

**Pull request merged**
