### PR TITLE
[FIXED JENKINS-29696] Allow parallel builds

### PR DESCRIPTION
**Pull request by mboersma**
This is the same as #121 but with a compliant commit message. Thank you to @bigwheel for fixing the code, and my apologies for this duplicate PR. I don't mean to intrude; we are just eager to get this fixed. :smile: 

Please close this if #121 gets updated.

### CODE REVIEW

**Comment by samrocketman** [comment]
Sure, mind taking a look at #106 as well?  That's currently holding up a release so when this gets merged it will still be held up by lack of a migration path.

**Comment by samrocketman** [comment]
You can refer to [jenkins-bootstrap-slac](https://github.com/samrocketman/jenkins-bootstrap-slack) as a quick playground and to see how the migration path currently fails when upgrading from stable to the latest master.

**Comment by samrocketman** [comment]
My computer died as I was working on testing this.  It may be a few more weeks before it's merged when I have a new one (posting from a tablet).

**Comment by ktf** [comment]
Any ETA for this to land in a release?

**Comment by samrocketman** [comment]
No ETA at this time; my development machine is toast at the moment along with my keys.  I'm working on recovering them.  In the mean time feel free to build slack plugin yourself, with this merged, and use it.

A release will _not_ happen until there's a migration path for #106.  Feel free to contribute to the migration.  I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by samrocketman** [comment]
I'm going to merge this into master after testing now.

**Comment by samrocketman** [comment]
Merged, thanks for your hard work.

**Comment by cxmcc** [comment]
We need a release with this fix...badly. Do you know when is this version going to be published?

**Comment by samrocketman** [comment]
@cxmcc A release will happen eventually.  In the mean time, I encourage you as well as others to contribute back to the project by addressing #106.  As always, the plugin can be manually built to get the fix.  So if you truly need this fix you could always build the plugin in the mean time.  I recommend building from the `slack-1.8-stable` to avoid upgrade issues with migrations.

**Pull request merged**
