### PR TITLE
Reducing "default" log verbosity

### PR DESCRIPTION
**Pull request by batmat**
Avoid having each successful post being logged by default.
(INFO is the JUL default level).

### CODE REVIEW

**Comment by batmat** [comment]
Ping @kmadel & @reviewbybees Thanks

**Comment by kmadel** [comment]
Look for some feedback from slack users regarding log level

**Comment by batmat** [comment]
Honestly, I don't have the energy do ask the community about that on the users list.

Imo it just does make sense: I noticed it working on some customer production logs where there were like 10th of **successful** posts logged in the global logs. 

As the default log level of Jenkins is INFO it makes actually important messages like errors far less visible.

WDYT @jenkinsci/code-reviewers (easy one)?
Thanks

**Comment by oleg-nenashev** [comment]
👍 from me. INFO log level is the default one for system logs, and it is not recommended to pollute by success-path info from build execution.

Maybe FINE, not FINEST

**Comment by batmat** [comment]
@kmadel feedback provided by @oleg-nenashev 

Just resolved conflict to enable merging. Could you please consider it again? As Oleg says, IMO it's just a matter of not filling the main server logs with success logs, making it harder to look for actually important messages. Thanks again

**Comment by kmadel** [comment]
@batmat - will merge as soon as Jenkins finishes.

**Comment by batmat** [comment]
Great, thanks.

2016-10-31 13:54 GMT+01:00 Kurt Madel <notifications@github.com>:

**Pull request merged**
