### PR TITLE
Add option to use Slack's Incoming Webhooks

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by bryant1410** [comment]
I see that this isn't working as expected, it doesn't let you choose between using Incoming Webhooks or the Integration App. How can I fix this in Jelly?

**Comment by kmadel** [comment]
Please fix merge conflicts.  

Need at least two thumbs up as well.

**Comment by kmadel** [comment]
Also, please update README.md with section about incoming webhook vs current config.

**Comment by MitchTalmadge** [comment]
👍

**Comment by samrocketman** [comment]
Please rebase this on master and resolve conflicts.  I'm stepping up to merge outstanding PRs for 2.2 release.

**Comment by bryant1410** [comment]
Hey, I won't be maintaining this branch because we have built a new plugin for this, [BuildSlackNotifier](https://github.com/xmartlabs/BuildSlackNotifier), which for some reason ended up being easier for us. But if someone wants to continue this branch, go ahead.

**Pull request closed without merging**
