### PR TITLE
Migrate job config settings to publishers section for updating from 1.8 to 2.0

### PR DESCRIPTION
**Pull request by OwensCode**
This is a fix for #106 and includes:

- Everything from PR 158 from @nevermindr
- Fixes for issues that were uncovered during testing of PR 158
- Unit tests for the migration under various scenarios

### CODE REVIEW

**Comment by kmadel** [comment]
I would like to merge this as part of the 2.0 release but need at least one more code review - anyone?

**Comment by kmadel** [comment]
Anyone else able/willing to test and review this PR?

**Comment by kmadel** [comment]
Tested locally against Jenkins core 1.642.2
Upgraded 1.8.1 to 2.0-snapshot with this PR, configuration was successfully migrated.

**Comment by kmadel** [comment]
@OwensCode It appears that the SlackProperty inner-class not having a descriptor is a fatal error in Jenkins 1.652 - see #188 

Would you be able to update with something similar to this from https://github.com/jenkinsci/hipchat-plugin/blob/master/src/main/java/jenkins/plugins/hipchat/HipChatNotifier.java:

```
        @Extension
        public static final class DescriptorImpl extends JobPropertyDescriptor {
            public String getDisplayName() {
                return "HipChat Notifications";
            }

            @Override
            public boolean isApplicable(Class<? extends Job> jobType) {
                return true;
            }

            @Override
            public HipChatJobProperty newInstance(StaplerRequest sr, JSONObject formData) throws hudson.model.Descriptor.FormException {
                return new HipChatJobProperty(sr.getParameter("hipChatProjectRoom"),
                        sr.getParameter("hipChatStartNotification") != null,
                        sr.getParameter("hipChatNotifyAborted") != null,
                        sr.getParameter("hipChatNotifyFailure") != null,
                        sr.getParameter("hipChatNotifyNotBuilt") != null,
                        sr.getParameter("hipChatNotifySuccess") != null,
                        sr.getParameter("hipChatNotifyUnstable") != null,
                        sr.getParameter("hipChatNotifyBackToNormal") != null);
            }
        }
```

**Comment by OwensCode** [comment]
I'll look into it.

**Pull request merged**
