### PR TITLE
Add build status to README

### PR DESCRIPTION
**Pull request by samrocketman**

### CODE REVIEW

**Comment by peergum** [comment]
the proper markdown syntax would rather be:
[Build Status](https://jenkins.ci.cloudbees.com/job/plugins/job/slack-plugin/)

**Comment by samrocketman** [comment]
Both syntax styles are proper markdown.  One is just using the links at the bottom.  I mostly use a terminal so my style of documentation is typically store all of the links at the bottom of the markdown page and the documentation is never more than 80 characters wide.  Here's an example of a README in another project of mine where all of the links are at the bottom.

https://raw.githubusercontent.com/samrocketman/jervis/master/README.md

**Comment by samrocketman** [comment]
See the Jenkins README rendered:
https://github.com/jenkinsci/slack-plugin/blob/build_status/README.md

**Comment by peergum** [comment]
Cool, I didn't know about that syntax... :-) (I ran it on sublime and it failed, so I supposed something was wrong... I must have done it wrong myself...)

**Comment by samrocketman** [comment]
If it's cool with you then I'll merge the change.  From now on any changes I make will no longer be direct commits but opened with pull requests like this one.  This way I'm not directly pushing to master without review.

**Comment by peergum** [comment]
Totally fine with me.

**Pull request merged**
