### PR TITLE
Fix #96 double start message when build is manually started

### LINKED ISSUE #96: multiple notifications for job start
I have the box checked to notify when builds start, and I always get multiple Slack messages:

```
Gallery build from pull request - #342 GitHub pull request #342 of commit d28d70c9ee16cc1190498b0f30ea308e1e313168, no merge conflicts.

Gallery build from pull request - #342 Started by changes from nobody, Christopher Smith (48 file(s) changed)
```

It would be simpler to have these post as a single message.

### PR DESCRIPTION
**Pull request by tterrag1098**
This isn't *technically* tested but I think the change is pretty obvious

### CODE REVIEW

**Comment by samrocketman** [comment]
I've marked this as a candidate to merge.  I'll test the behavior and if it behaves as expected then I'll merge it.  If not, I'll respond why.

**Comment by tterrag1098** [comment]
Just a note, I built my branch myself and installed it on my jenkins, and I could not see any of the slack options. Did something large change that I could have missed?

**Comment by samrocketman** [comment]
Seems some information was lost in the patch.  Here's a snapshot of behavior before/after.

snapshot of before and after

Seems there's some information lost when combining the two messages.  @chrylis does this make sense or is your desire to have all contents combined?

I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by tterrag1098** [comment]
The behavior I was testing against was the behavior of the current release, which is evidently different than the behavior of the master branch. Though I don't really see the purpose of the "Starting..." message either. Isn't it a bit redundant?

**Comment by samrocketman** [comment]
The master branch significantly differs currently from the latest stable release.  Therefore, it should be tested from `master`.  It is redundant which is why this is being address by your pull request, correct?  The missing information I'm referring to is "started after 2.1 sec".  If you have a lot of jobs queued up and the job spent time in the Jenkins build queue then this time would be longer.  So I don't think it's necessarily bad to have the information.

That's why I'm waiting on @chrylis to respond with what they originally intended.  I have no qualms either way as I do not currently use the slack plugin.  I maintain it for others who wish to contribute to its code base.

**Comment by samrocketman** [comment]
Since not much feedback has been received from @chrylis I'm going to go ahead and approve this pull request as a candidate to merge.

**Comment by MilesRoberts** [comment]
@samrocketman: the test you posted looks like it dumps and/or ignores the custom message from the start messaging. Am I reading that right?

**Comment by GuiSim** [comment]
Any plans on merging this?

**Comment by samrocketman** [comment]
@MilesRoberts feel free to open an issue and perhaps a PR to address the issue.

**Pull request merged**
