### PR TITLE
samrocketman no longer maintainer

### PR DESCRIPTION
**Pull request by samrocketman**
I've tried to effectively find someone who is willing to go through this plugin and lead on its design.  As of now, I'm no longer maintaining it and am officially dropping my maintenance of it.  If you wish, step up and actively maintain this plugin to drive its direction and development.  Maintaining this has been an interesting experience for me considering I don't use the plugin in practice.  I feel it would be in much better hands for someone with drive.

I apologize if this inconveniences any of you but I currently wish to focus my time elsewhere.

Thanks,
SAM

### CODE REVIEW

**Comment by vkotovv** [comment]
That's sad. Maybe you should put something like "No longer maintained, looking for a new maintainer" at the beginning of Readme?

**Comment by samrocketman** [comment]
@vkotovv Thanks for the suggestion.  As of now the plugin is comaintained by @kmadel and @gurumaia.  This PR was me officially stepping down.

**Comment by vkotovv** [comment]
@samrocketman I've added this repo to https://github.com/pickhardt/maintainers-wanted recently, maybe it should be removed then.

**Comment by johnjohndoe** [comment]
Has @timja stepped up to lead this project?

**Comment by timja** [comment]
yes...

**Comment by johnjohndoe** [comment]
Great. Should we remove this project from https://github.com/pickhardt/maintainers-wanted?

**Comment by timja** [comment]
please

**Pull request merged**
