### PR TITLE
Fix #126 Replace <a> tags with Slack <link|name>

### LINKED ISSUE #126: Formatting/ escaping issue with Bitbucket Pull Request plugin
I tried using the Bitbucket Pull Request plugin https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin, and the slack messages posted from this job is not escaped probably. This is what I see

```
#10 <a href="https://bitbucket.org/myorg/myrepo/pull-request/367">#367 Consolidate jsdoc and styleguide into a single doc</a> (Open)
```

I am not sure if this is an issue with this plugin, or the pull request plugin. I figured I should file this here first.

### PR DESCRIPTION
**Pull request by frodeaa**
Replace `<a href...>text</a>` with `<url|text>` before
escaping the remaining parts of the message

fixes #126
fixes nishio-dens/bitbucket-pullrequest-builder-plugin#59

### CODE REVIEW

**Comment by facastagnini** [comment]
@kmadel can this please be merged?

Thanks a lot

**Comment by mskutin** [comment]
@kmadel could you please take a look at this PR?

**Comment by jgangemi** [comment]
any chance this could be rebased and reviewed so it gets included in the 2.1 release? i'd really love to see this fixed.

**Comment by kmadel** [comment]
Once latest changes are merged from master, this is a candidate for 2.2

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.

**Pull request merged**
