### PR TITLE
Simplify and Groovyfy attachment handling

### PR DESCRIPTION
**Pull request by mguillem**
Finally the complete pull request to handle attachments "in a Groovy way".

The original idea was here: https://github.com/jenkinsci/slack-plugin/pull/392 but it was still requiring an import that had to be whitelisted. This is not the case anymore and this change is particularly interesting as it removes the need for whitelisting JSONArray and JSONObject when using attachments.

### CODE REVIEW

**Comment by mguillem** [comment]
import order changed (without explicit rules for the expected order it is just a requirement to demotivate contributors :-()

**Comment by timja** [comment]
Without explicit rules the default is always minimal change, which may mean deactivating auto import in the project you are in.

I will look at enforcing it with checkstyle soon

**Comment by casz** [comment]
@timja codacy has support for reading checkstyle rules but you can also setup Jenkinsci to do it, but it is a lot slower.

Code climate is another option

**Comment by casz** [comment]
on JCasC I would properly switch to code climate instead of codacy, https://docs.codeclimate.com/docs/checkstyle better documentation and better config

**Comment by timja** [comment]
@casz checkstyle is already run as part of the build, there's just minimal rules.
I have a local branch but never finished cleaning up the codebase for it.

**Pull request merged**
