### PR TITLE
Fixes issue #125 where this plugin is nested inside another publisher

### PR DESCRIPTION
**Pull request by andrewbonney**
This is a fix for notifications failing when the Slack publisher is nested within another post-build action such as a conditional action or a template.

Unless I'm missing something it seems unnecessary to have a separate listener for build events outside of the core Notifier implementation. This may simply have been here for legacy reasons, but it makes it difficult to identify which Publisher(s) to run.

I'm going to run a few more tests on this locally in case I'm missing something obvious and breaking anything, but would welcome any comments.

### CODE REVIEW

**Comment by MichaelKueller** [comment]
I'm highly interested in this PR. What can I do to get it merged quicker?

**Comment by ericwengelking** [comment]
I'm very interested in this as well

**Comment by JohannaVarga** [comment]
Hi,
I'm also very interested in this. Could you please review and merge this branch? It would be awesome!

**Comment by ntulele** [comment]
I'd also love to have this reviewed & merged....

**Comment by adamerstelle** [comment]
Really wanting this to be available, when is 2.4 going to be released?

**Pull request merged**
