### PR TITLE
Allow parallel builds

### PR DESCRIPTION
**Pull request by bigwheel**
This will resolve https://issues.jenkins-ci.org/browse/JENKINS-29696.

Thank you for help, @mimimizu.

### CODE REVIEW

**Comment by samrocketman** [comment]
Please ammend your commit message to include `[JENKINS-29696]`.  That way the Jenkins bot posts in the issue.

**Comment by mboersma** [comment]
:+1: The default serialized behavior for a post-build plugin seriously limits the throughput of our Jenkins instance. At any given moment, more than half of the "running" jobs are just waiting for a useless checkpoint on another job. Thank you for tackling this @bigwheel.

**Comment by krancour** [comment]
:100:

**Comment by bigwheel** [comment]
@mboersma Sorry for slow response, I went summer vacation.
Thank you #122, then Should I close this pull request?

**Comment by mboersma** [comment]
@bigwheel you could fix the commit message and then I'll close #122. Or we can close this one if you prefer. Sorry to confuse things.

Note that #106 needs to be fixed before a new Slack plugin goes out, so that effectively blocks this change being released to users.

**Comment by bigwheel** [comment]
@mboersma sorry for very late response.

> @bigwheel you could fix the commit message and then I'll close #122. Or we can close this one if you prefer. Sorry to confuse things.

I decide to close this PR. Thanks much support :)

**Comment by yoyobbi** [comment]
I would like to get this fix, but my Jenkins doesn't see an updated version of the Slack Notification plugin yet. Should I expect to see an update soon?

**Comment by samrocketman** [comment]
@yoyobbi the next update (of which this is included) is blocked by #106.  Please feel free to contribute a fix.  I only maintain pull requests and releases.  I do not actively develop this plugin.

**Comment by yoyobbi** [comment]
I see, understood. I haven't made the leap to Jenkins plugin development yet, so I will selfishly sit back and wait.

**Pull request closed without merging**
