### PR TITLE
Team domain and integration token per project (moved from global settings)

### LINKED ISSUE #10: One jenkins multiple teams
Hi,

we have one Jenkins instance and multiple Slack teams (projects). Current plugin in global settings defines Slack "secrets" so you can't configure it for multiple teams.
So either put this to the build configuration or enable definition of Teams in th global settings where a value can be than picked for a specific build.
This is quite a showstopper for our case.

Can I expect the fix in a reasonable time or do we have to make a change ourselves?

thanks in advance

Peter

### PR DESCRIPTION
**Pull request by idserda**
This resolves #10.

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
Please, merge it. :+1:

**Comment by samrocketman** [comment]
I guess I'll start maintaining this.  I don't have any experience developing Jenkins plugins but if I can get my own environment set up and learn to release then I'll do it.  This may take about a week.

**Comment by samrocketman** [comment]
Candidate for merge means I will first merge your change locally, compile locally, and test locally in Jenkins before merging.

**Comment by samrocketman** [comment]
In the next release you'll find the Advanced section at the bottom of the slack configuration area.

**Pull request merged**
