### PR TITLE
Send more advanced slack messages v2

### PR DESCRIPTION
**Pull request by gurumaia**
Based on @ahmetrehaseker's implementation.
This is a change to support slack complex messaging.
See #285 for more details.

### CODE REVIEW

**Comment by gurumaia** [comment]
Can someone review this?

**Comment by samrocketman** [comment]
Hey @gurumaia, I'll take a look as well and try bootstrapping it with my project.  Please also refer to #320 as I generally am attempting to distance myself from this plugin specifically.

**Comment by gurumaia** [comment]
Alright, great @samrocketman. I did see your commits about removing yourself as a maintainer. I can try to step up and help maintain the plugin if you'd like.

**Comment by samrocketman** [comment]
@gurumaia you're welcome to step up and maintain.  Feel free to check in with @kmadel who, as far as I know, has not relinquished being the other maintainer.  I'm sure he wouldn't mind bringing you on board.  Feel free to send a message to the developers mailing list, mention Kurt, and this discussion.

**Comment by djk** [comment]
Would be amazing to have this reviewed and hopefully approved. Is @gurumaia taking it over?

**Comment by gurumaia** [comment]
Hey @djk I'll contact @kmadel to see if I can get in. This has been on the back of my mind lately as I've had quite a few rushed days these past few weeks.
Btw, the plugin has been working nicely in my production environment. While this isn't approved, feel free to clone my repo and build using the instructions in the readme.

**Comment by djk** [comment]
Thanks @gurumaia, I'll check your repo! 

Wasn't hassling you, hope it doesn't feel that way. Thanks for the great work.

**Comment by gurumaia** [comment]
Absolutely no hassling =).

btw, I didn't actually code this, I just took @ahmetrehaseker's old PR and performed @samrocketman's suggestions.

**Comment by djk** [comment]
@gurumaia 

Ah right, well thanks to @ahmetrehaseker and @samrocketman too!

One thing, not sure where best to mention this but does your PR support "fields": https://api.slack.com/docs/message-attachments#fields

I'm not quite sure how one would enter a JSON array into the example that you provided on the page of your fork.

Thanks again!

**Comment by gurumaia** [comment]
@djk sorry, I missed your edit.
The code you posted seems like it should work fine. What value are you getting in slack?
For reference, here's an example from one of my internal projects:

```
        String artifactUrl = "${env.NEXUS_URL_NOTIFY}${env.pom_groupId}/${env.pom_artifactId}/${env.pom_new_version}/${env.pom_artifactId}-${env.pom_new_version}.${env.pom_packaging}"

        JSONArray fields = new JSONArray();
        JSONObject field = new JSONObject();
        field.put('title','URL Nexus');
        field.put('value',artifactUrl);
        fields.add(field);
        attachment.put('fields',fields);
```
@kmadel If you could review this PR, I can go ahead and merge it.
Thanks

**Comment by kmadel** [comment]
Decent doc update, it has tests, looks ok to me. I so go for it @gurumaia and thanks.

**Comment by rafi-tvtime** [comment]
Is this being merged?

**Comment by brianespinosa** [comment]
+1 for this feature getting merged now that it appears to have tests and looks good.

**Comment by gurumaia** [comment]
I've merged and now I'm waiting for approval on my request for upload access to actually release it: https://github.com/jenkins-infra/repository-permissions-updater/pull/399

**Comment by brianespinosa** [comment]
@gurumaia Any idea on timing to release this? I noticed that your above referenced PR giving you access has been merged. Thanks again for your help taking this over.

**Comment by gurumaia** [comment]
Hey @brianespinosa I've finally released it to the update center yesterday. Should be available now. Please test it and let me know if it works well for you.

**Comment by mtthoyle** [comment]
Doesn't this revert the fix in https://github.com/jenkinsci/slack-plugin/commit/3905e006d8dc7ef7295ab9e3ebda9b745a38806f#diff-282db0eb13a24d1729df3e194a35f6d7  #274 made by @p00j4 ?
So that messages over 4K will be truncated again. Because that is at least what I am seeing in version 2.3.

**Pull request merged**
