### PR TITLE
Add null check and log

### PR DESCRIPTION
**Pull request by timp21337**

### CODE REVIEW

**Comment by samrocketman** [comment]
I guess I'll start maintaining this plugin.  I don't have any experience developing Jenkins plugins but if I can get my own environment set up and learn to release then I'll do it.  This may take about a week.

**Comment by timp21337** [comment]
We are using this plugin, with this patch applied.

**Comment by samrocketman** [comment]
It looks okay to me.

**Comment by samrocketman** [comment]
Candidate for merge means I will first merge your change locally, compile locally, and test locally in Jenkins before merging.

**Pull request merged**
