### PR TITLE
Enhance Custom Message Functionality

### PR DESCRIPTION
**Pull request by csogilvie**
This enhances the custom message functionality to include both a default custom message, if defined, and a specific custom message per build failure types.

### CODE REVIEW

**Comment by oppai** [comment]
:+1:

**Comment by Nooba** [comment]
Was looking for this. Thanks !

**Comment by brandonroeder** [comment]
Any update on this?

**Comment by markusbergh** [comment]
Any update on this?

**Comment by kmadel** [comment]
Need at least two thumbs up if this is going to make it into 2.0

**Comment by brandonroeder** [comment]
Well here's one thumb 👍

**Comment by samrocketman** [comment]
Needs to be updated to resolve conflicts.

**Comment by samrocketman** [comment]
Seems to fix issue #163.

**Comment by csogilvie** [comment]
I have updated this branch with the conflicts resolved.

**Comment by samrocketman** [comment]
All I see is:

> This branch is out-of-date with the base branch
Merge the latest changes from master into this branch.

**Comment by csogilvie** [comment]
Unless I've missed something, this is merged now, according to Github - although it's pending the Jenkins validation at the moment.

**Comment by samrocketman** [comment]
Would you mind rebasing to discard the merge commits.  e.g.

```bash
cd /path/to/your/slack-plugin
git checkout variable-custom-messages
git remote add upstream git@github.com:jenkinsci/slack-plugin.git
git fetch upstream
git rebase upstream/master
git push origin variable-custom-messages --force
```

The rebase will auto-discard the merge commits.

**Comment by csogilvie** [comment]
Done - sorry, my first time using git in anger :)

**Comment by samrocketman** [comment]
Thanks.  I'll let Kurt perform the merge.  Definitely much cleaner.

**Comment by csogilvie** [comment]
Any update on this?

**Comment by samrocketman** [comment]
@kmadel ^^

**Comment by ElijahLynn** [comment]
@csogilvie Can you get this rebased off master again? It isn't mergeable right now.

**Comment by csogilvie** [comment]
I will rebase, test and verify this again, however, this time I would like to see some action on it, rather than it just hanging around... as it is not a good way to encourage contributors :(

**Comment by csogilvie** [comment]
This seems to check out OK from my testing.

**Comment by ElijahLynn** [comment]
@csogilvie Thanks! I will try to get this tested out soon. Our Jenkin's looks like it needs to be updated in order to use the 2.x version of this plugin. Gotta get that updated now.

**Comment by csogilvie** [comment]
I have rebased this again today as I noticed it had an issue.

**Comment by kmadel** [comment]
Please fix merge conflicts

**Comment by csogilvie** [comment]
Done, again.

**Comment by kmadel** [comment]
This is a top candidate for 2.2 - please merge latest from master

**Comment by jgangemi** [comment]
any update on this making the 2.2 release?

**Comment by samrocketman** [comment]
Please squash this into one commit and rebase on `master`.  I've decided to step up and merge/release outstanding pull requests after some of my own manual testing.

**Comment by csogilvie** [comment]
I have squashed these and rebased it.

**Comment by samrocketman** [comment]
Awesome I'll test/merge this evening.

**Comment by samrocketman** [comment]
@csogilvie I've posted my review.  Let me know if you have any questions.  As soon as a plugin upgrade cleanly upgrades (without affecting) existing configurations I will consider it good to merge.

**Comment by hsson** [comment]
Is there any progress update on this, @csogilvie ? It's a feature that would be really great to have for our use cases.

**Comment by oshmyrko** [comment]
:+1:

**Comment by MikePryn** [comment]
:+1:

**Comment by AnneTheAgile** [comment]
@kmadel is there a way for regular users who haven't checked out to see what the conflict is? 
@csogilvie possibly is occupied, though started this and did many updates before you came and started newly maintaining.

**Comment by kmadel** [comment]
I will take a look once you merge changes from masters, looks like parts of this were already added/fixed by other merges.

**Comment by timja** [comment]
Closing this now to clean up the repo,
if this is still wanted, please resolve conflicts and reopen

**Pull request closed without merging**
