### PR TITLE
Add Slack mentions for commit authors

### PR DESCRIPTION
**Pull request by fstehle**
This PR enables the plugin to lookup the Slack ID of a commit author by his email address and mention him when publishing the list of commits with authors:

slack_mentions

### CODE REVIEW

**Comment by MobileOak** [comment]
@fstehle I've looked through your code change trying to understand how it is that the '@ mention' is converted from plain text to an actual notification to the user, and can't seem to find out how this is accomplished. I am trying to work with my build engineer to trigger an '@here' custom message when the build fails for any reason, but when that field is populated, it prints it in plain text in the channel instead. I was hoping to come up with a simple patch to solve that and submit it (or maybe this functionality is already present?? there's so little documentation here). Any tips?

**Comment by samrocketman** [comment]
@MobileOak seems it does it here: https://github.com/jenkinsci/slack-plugin/pull/178/files#diff-6e57cc81ad99f23910d2db31ec1d1dd8R201

To quote:
```
<@username>
```

**Comment by Bonko** [comment]
any news about this?

**Comment by fungusakafungus** [comment]
Rebased this on master and clicktested on local jenkins, works for me.

**Comment by LarsOL** [comment]
Can this be merged? It would be very useful.

**Comment by PirminTapken** [comment]
@kmadel PTAL and merge, if you're ok with it. If there's anything missing, don't hesitate to tell us (@fstehle @fungusakafungus @bonko).

@MobileOak This change only checks if the mail address used in the merge commit is used by a slack user and then uses that username. Nothing else.

**Comment by fstehle** [comment]
@kmadel what is the status here? 
Is there anything missing in order to get this merged?

**Comment by kmadel** [comment]
@fstehle #247 is considered a severe security issue per Jira - so until we can get one more thumbs up on that PR and get it merged and release, there will no other merges.

**Comment by Szasza** [comment]
https://github.com/jenkinsci/slack-plugin/pull/247 is merged, but now there are conflicts in this PR. @fstehle would it be possible to please resolve them?

Thank you.

**Comment by fstehle** [comment]
@Szasza @kmadel I resolved the conflicts and tested the branch with our Jenkins setup. Everything seems to work. Could you approve this again please?

**Comment by Skilgarriff** [comment]
Any update on this?

**Comment by zach-nervana** [comment]
any more updates?  It looks so close

**Comment by samrocketman** [comment]
Please merge and resolve conflicts with the latest master.  I've decided to step up and merge/release outstanding pull requests.

**Comment by samrocketman** [comment]
I plan on performing a release this weekend. If you would like this PR to be in it then please rebase/resolve.

**Comment by samrocketman** [comment]
@fstehle do you mind merging master into this PR and resolving conflicts?  Additionally, would you mind giving me write access to your repository so I can help you clean up your commits after you resolve the conflicts?

**Comment by samrocketman** [comment]
cc @bracki see my previous comment.

**Comment by bracki** [comment]
@samrocketman I gave you access as requested.

**Comment by samrocketman** [comment]
@bracki thanks, I got the access.  I won't be able to resolve the merge conflicts though.  I'm not very familiar with the changes and am a relatively green Java dev.  So unless someone can help me out by resolving the conflicts there's not much I can do at this time.

**Comment by smon** [comment]
@samrocketman we resolved the conflicts - be quick ;)

**Comment by samrocketman** [comment]
I'll be testing before I merge it.

**Comment by samrocketman** [comment]
I am going to test this now.  I'll either merge it or post feedback.

**Comment by roni-frantchi** [comment]
> I am going to test this now. I'll either merge it or post feedback

@samrocketman so.. did it work?..

**Comment by LarsOL** [comment]
Right now we are blindly grabbing the firstname.lastname from the git commit info, is there a way of doing this inside a pipeline? It would be more reliable to lookup via email

**Comment by smon** [comment]
@LarsOL The slackid lookup is done by email in this PR [here](https://github.com/Jimdo/slack-plugin/blob/8fce36aaf2d0285f89a2b918def287eb8595ddde/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L250) - or are you referring to something different?

**Comment by LarsOL** [comment]
Sorry, I was asking if this lookup is available in the pipeline script?

**Comment by Bonko** [comment]
@samrocketman according to your description, I assume you did not set an API Token?

**Comment by samrocketman** [comment]
@Bonko can you elaborate?  If you're referring to a slack API token, then it was configured.  It is automatically configured on bootstrap.

**Comment by Bonko** [comment]
@samrocketman in your [bootstrap documentation](https://github.com/samrocketman/jenkins-bootstrap-slack) an integration token is set. This PR introduces an API token, which has to be set as well.

However, the plugin should not break when it is not send, but just dont link to the authors in my opinion

**Comment by samrocketman** [comment]
Thanks for clarifying.  I'll retest with API token but still desire an upgrade to minimally affect existing users as per my review comment.

**Comment by samrocketman** [comment]
I'll wait to retest this when upgrades are resolved.

**Comment by fstehle** [comment]
> Unfortunately, this can't be merged as-is.
> 
>  ...
>  Regression: This plugin breaks listing changes entirely when posting to slack. (the first bullet point is related to this). It breaks an existing feature that worked pre-upgrade to this change.

@samrocketman @kmadel we fixed the plugin in order to avoid breaking listing of changes when the new API token is not set.

**Comment by samrocketman** [comment]
I'll try and retest this.

**Comment by fstehle** [comment]
@samrocketman Already any updates on this?

**Comment by chachi** [comment]
Bump. Any updates on the inclusion of this awesome feature?

**Comment by eyalzek** [comment]
I ended up creating a simple bot to intercept bot messages (in my case, messages starting with `INPUT`), extract the name of the person from the message and then relay it as a DM. Here's the code if anyone's interested:
https://gist.github.com/eyalzek/89bf09df9e76a0d03e09abd3198f51e0

**Comment by PirminTapken** [comment]
@samrocketman is there a way we can help you for testing / approval?

**Comment by jeffpearce** [comment]
Would love to see this published as well

**Comment by samrocketman** [comment]
Hi all, for context I have already passed on ownership of this plugin to other people.  Just letting you know here since it may not be obvious.  Please refer to https://github.com/jenkinsci/slack-plugin/pull/320

**Comment by delmartechdude** [comment]
@kmadel @gurumaia Anything we can do to help get this merged?

**Comment by iakovmarkov** [comment]
@kmadel @gurumaia is there anything preventing this PR from getting merged? Would love to use this as well, please let us know if we can help with the PR somehow.

**Comment by AnneTheAgile** [comment]
@fstehle ^^ maybe you can fix the conflicts or describe them?

**Comment by timja** [comment]
Closing this now to clean up the repo,
if this is still wanted, please resolve conflicts and reopen

anyone can send the PR

**Comment by evgeniyQAA** [comment]
Pls deploy this feature

**Comment by timja** [comment]
@evgeniyQAA if you can resolve the conflicts and send a PR I can look at getting it in

**Comment by johnjohndoe** [comment]
Since it looks like to me that @timja stepped up to maintain this project [following after](https://github.com/jenkinsci/slack-plugin/pull/178#issuecomment-369704846) @samrocketman I want to politely ask @fstehle if you will continue working on this feature?

**Comment by fstehle** [comment]
I can't work on this at the moment. Maybe someone else want to create a new PR for that?

**Comment by rodrigc** [comment]
@fstehle very nice patch!  Excellent work!

**Comment by johnjohndoe** [comment]
@fstehle Thank you for the status update.

**Comment by kajabfab** [comment]
Can someone help me with sample code on how to use this feature?

**Comment by davidrochin** [comment]
Any updates on this?

**Pull request closed without merging**
