### PR TITLE
Enhance Custom Message Functionality (rebased from #169)

### PR DESCRIPTION
**Pull request by KreAch3R**
The bd28d4e065fbfe419e6c79d24336f4b25abad156 is a very valuable commit. It makes or breaks the `slack-plugin` experience for me. I took the time to merge it into the current master branch, and fix any problems that arose.

I have no idea how to fix the migration problems that #169 mentioned as the reason of no merge. In my experience, I just had to `configure` the project once and then save it. Afterwards, I could move the custom message where I wanted and it works.

I'm PRing this so that others can see and use it locally.

### CODE REVIEW

**Comment by timja** [comment]
Needs conflicts fixing

**Comment by timja** [comment]
feel free to reopen when you resolve conflicts

**Comment by KreAch3R** [comment]
Hey @timja , thanks for taking over/updating this repo. I took a look at what changes are made so the original #169 commit can be merged in the current master. 

It seems that with your commit: https://github.com/jenkinsci/slack-plugin/commit/e1d919a319613e6338e853c392cfdac826e8b825 you changed an important part of this commit, mainly the method `newInstance`, where this part was added:
https://github.com/jenkinsci/slack-plugin/blob/bd28d4e065fbfe419e6c79d24336f4b25abad156/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L447-L452

I tried to follow your commit and do the appropriate changes on top of that, but I don't know how to add that HashMap as you did (in your config jelly changes).

Any ideas on that? I'd love to get this #169 commit merged into mainline. It works beautifully.

**Comment by timja** [comment]
The jelly changes require matching getters and setters, with the setters annotated with `@DataboundSetter`

**Comment by KreAch3R** [comment]
Ok, so should I try to create a setter that creates that customMessageMap? I'm not sure how jelly will/can handle it, since it's not a simple "value get". It's a Map with values and Results and there is a custom getCustomMessage(String buildType) command that returns the correspondent value. 

Any pointers would be appreciated.

**Comment by timja** [comment]
I've never tried a map, if you want to continue down that path I would ask:
on gitter,
or IRC
or mailing list

otherwise you could store all the fields on the object directly as from looking at the ui it just seemed to be more fields?
and then add a method to retrieve the right message?

**Pull request closed without merging**
