### PR TITLE
Only try to parse response as JSON if Content-Type is application/json

### PR DESCRIPTION
**Pull request by rodrigc**
Fixes https://github.com/jenkinsci/slack-plugin/issues/594

### CODE REVIEW

**Comment by rodrigc** [comment]
As I mentioned here: https://github.com/jenkinsci/slack-plugin/issues/594#issuecomment-524482233

I'm still seeing errors where Slack returns a response where the HTTP code is 200,
and the payload is just the string **ok** which is not in JSON format.

```
Aug 23, 2019 10:31:20 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed.  Invalid JSON response: ok
Aug 23, 2019 10:31:20 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed. Response: ok
Aug 23, 2019 10:31:20 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Response Code: 200
```

**Comment by casz** [comment]
This is not really a fix as result is used in pipeline scripts.

**Comment by casz** [comment]
Perhaps a simpler solution is to check if the string response is just `ok`.

**Comment by timja** [comment]
Still need to get to the bottom of why, this shouldnt be happening and is likely misconfiguration. I would like to get that fixed and documentation improved

**Comment by rodrigc** [comment]
@casz If you look at my patch in the context of the function which it is used, you will see that I did not remove `result`.  `result` is still returned as *true* from the function of the HTTP response code is 200 (for success), and returns `false` otherwise.

**Comment by rodrigc** [comment]
@timja this is not a misconfiguration.  It looks like if you use an override URL, the HTTP response returns `ok` but not JSON formatted.

Looks like this has come up for other people like here:

* https://github.com/slackapi/node-slack-sdk/issues/501
* https://github.com/slackapi/node-slack-sdk/pull/480

**Comment by rodrigc** [comment]
@casz OK, I changed the patch to only try to parse the response as JSON if the **Content-Type** of the response is **application/json**.

**Comment by timja** [comment]
But why are you using an override url?

**Comment by rodrigc** [comment]
My token only works if the override URL is specified

**Comment by timja** [comment]
What’s the override url you are using? You can replace your company domain with example :)

**Comment by rodrigc** [comment]
I'm using: https://mycompany.slack.com/services/hooks/jenkins-ci/

**Comment by timja** [comment]
The change I would take instead would be if the override url is set to the Jenkins-ci url on the slack domain to force it down the correct code path. I’ll make the change next week when I’m back, unless you want to...

**Comment by rodrigc** [comment]
I don't understand the slack-plugin code enough to make the change that you requested.

**Comment by timja** [comment]
@rodrigc can you test the incremental version from https://github.com/jenkinsci/slack-plugin/pull/624 please

**Comment by rodrigc** [comment]
Tested #624 here: https://github.com/jenkinsci/slack-plugin/pull/624#issuecomment-531491287

**Comment by timja** [comment]
Resolved in https://github.com/jenkinsci/slack-plugin/pull/624

**Pull request closed without merging**
