### PR TITLE
Add class name to failed test notification

### LINKED ISSUE #321: Enhance "Include failed Tests" Feature -> Link and Classname
Currently the include failed Tests feature only posts the Test that failed. It would be nice to also see the Classname like: MyTestClass.testMyFailedTest and also a direct link to the failed Test inside Jenkins

### PR DESCRIPTION
**Pull request by kiview**
Uses the className.methodName if the fullDisplayName is in the Java format or the fullDisplayName else.
Or is this something that should be configurable?

Fixes #321

### CODE REVIEW

**Comment by timja** [comment]
Can you attach a screenshot of before and after your change please?

**Comment by timja** [comment]
@kiview ?

**Comment by kiview** [comment]
I'll upload the screenshot tomorrow after I've checked with the team if it's okay to use one from our current project (should be fine though).

**Comment by timja** [comment]
@kiview  nudge

**Comment by kiview** [comment]
@timja Sorry for letting you waiting, had to check if it's okay:

jenkins_before

jenkins_after

**Comment by timja** [comment]
Thanks for the screenshot, looks great
Good addition

**Pull request merged**
