### PR TITLE
Fix for Slack notification plugin error proxy #102 

### PR DESCRIPTION
**Pull request by nevermindr**

### CODE REVIEW

**Comment by samrocketman** [comment]
Thanks for this contribution.  I'm going to open it up for code review.  In the mean time, if you don't mind take a look at #106 which needs to be implemented before the next major release.  I appreciate any time you're willing to contribute to resolving it.

I don't actively develop this plugin.  I only maintain pull requests and releases for the community that uses it.

**Comment by tonka3000** [comment]
Is there any release date for this issue? We have also that problem with the proxy.

**Comment by kmadel** [comment]
@nevermindr Please fix merge conflict.

**Comment by kmadel** [comment]
@nevermindr This is a fairly large set of changes and they aren' linked to an existing issue. It would be useful to have more information around exactly the kind of issues you have been having with the current HttpClient based approach.

**Comment by tonka3000** [comment]
hey @kmadel,

i'm not @nevermindr , but i can explain the issue a little bit.
The slack-plugin does not give the correct credentials to the proxy (with ntlm/kerberos auth) => so the log always say "wrong ntlm hash" (or something like that).
I hope that explain the issue a little bit.

I'm no java specialist, but the pr seems ok to me 😉 

Greetings
Tonka

**Comment by mattumotu** [comment]
Has there been any progress on this issue? It fixes an issue with the slack plugin detailed here: https://github.com/jenkinsci/slack-plugin/issues/102

**Comment by samrocketman** [comment]
Please update this PR and resolve conflicts.

**Comment by samrocketman** [comment]
I plan on performing a release this weekend.  If you would like this PR to be in it then please rebase/resolve.

**Comment by samrocketman** [comment]
Closing in favor of #299

**Pull request closed without merging**
