### PR TITLE
Added Groovy script example

### PR DESCRIPTION
**Pull request by ivan-pinatti**
Hi,

I've added to the README a how-to example to configure the plugin through Groovy script in order to be able to automate Jenkins configuration.

I also posted the same example in the [Plugin wiki page](https://wiki.jenkins.io/display/JENKINS/Slack+Plugin).

Cheers!

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
I haven't checked this yet but if it works it seems very great documentation to be added!
Bump for new maintainer .

**Comment by kmadel** [comment]
With the addition of JCasC support, not sure this is needed or still wanted. Thoughts?

**Comment by ivan-pinatti** [comment]
I think that it doesn't hurt to have it as it is already done, more options the better IMHO.

**Comment by timja** [comment]
I have doubts that this still works after the JCasC changes to use natural databinding,
all the UI fields were renamed to match the model fields

so anyone pretending to be the UI would need to update their field names or use JCasC

**Comment by timja** [comment]
@ivan-pinatti happy to merge it if you're able to test off the master branch and check it works?

**Comment by timja** [comment]
Feel free to reopen after resolving conflicts and testing it out 👍

**Pull request closed without merging**
