### PR TITLE
Updated to show the list of commits (title+author)

### PR DESCRIPTION
**Pull request by peergum**
when build is successful and if the corresponding option
is selected in the build's configuration (true by default)
and corrected buildServerUrl display format

### CODE REVIEW

**Comment by samrocketman** [comment]
I guess I'll start maintaining this plugin.  I don't have any experience developing Jenkins plugins but if I can get my own environment set up and learn to release then I'll do it.  This may take about a week.

**Comment by samrocketman** [comment]
Can you drag in a screenshot?  I'm curious what this looks like.

**Comment by samrocketman** [comment]
Can you pull in the latest changes from `master` because your project produces more merge conflicts than I can resolve.  See #37 for a description of what I similarly tried to resolve your conflicts.

**Comment by peergum** [comment]
I solved the conflicts with current HEAD.
Here's a sample of commit details shown on a successful build:
screen shot 2015-02-01 at 9 26 10 pm
The display of commit details can be enabled by checking a box in the advanced section of the config (only on successful builds - not sure there is an interest in showing these for failures...)

**Comment by samrocketman** [comment]
Candidate for merge means I will first merge your change locally, compile locally, and test locally in Jenkins before merging.

**Comment by samrocketman** [comment]
In 34b070946123d7539675143c7979792e0872eb4e, I combined the two advanced sections and placed them at the bottom.

**Comment by peergum** [comment]
Great. Thanks!

**Pull request merged**
