### PR TITLE
add "Include failed Tests"

### PR DESCRIPTION
**Pull request by SuperTux88**
includes all failed tests when some tests failed. does nothing if no failed tests were found

### CODE REVIEW

**Comment by kmadel** [comment]
Need some reviews on this one.

**Comment by ShimiTaNaka** [comment]
+1

**Comment by samrocketman** [comment]
It would be good if you wrote a couple tests that actually tests your code.  Otherwise, your code could be easily broken in the future.

e.g. Test when the setting is enabled and test when it is disabled.

**Comment by ShimiTaNaka** [comment]
Guys, I really really need this feature.
Given that the ActiveNotifier doesn't have any tests, and this PR only appends to it (small data), can we still integrate it?

**Comment by samrocketman** [comment]
Much of the code doesn't have tests.  Which is a primary reason this code is in such a poor state.  That and not having a clear direction or vision.  This plugin is quickly approaching feature creep.  It's unfortunate slack abandoned it.  IMO it could use a complete rewrite with clear vision.

Aside from my opinions I have no problems with this merging but I don't plan to merge it.  I leave it to @kmadel.

**Comment by samrocketman** [comment]
@SuperTux88 please resolve conflicts.  You might have guessed; but I've decided to step up and merge outstanding pull requests.

**Comment by samrocketman** [comment]
Also, a few tests would be desirable if you don't wish this feature to be broken in the future.  It helps prevent regressions by adding tests.

**Comment by SuperTux88** [comment]
> Also, a few tests would be desirable if you don't wish this feature to be broken in the future.

I don't need this anymore (because I no longer work in the company where we used slack), but I resolved the conflict and rebased.

**Comment by samrocketman** [comment]
@SuperTux88 
> I don't need this anymore (because I no longer work in the company where we used slack), but I resolved the conflict and rebased.

Thanks for stepping up to work on these PRs anyways :)

**Comment by samrocketman** [comment]
Darn, GitHub pulled a fast one on me.  Please rebase on `origin/master` one more time.  There's a merge commit with `+0/-0` changes.

**Comment by SuperTux88** [comment]
Yeah, I just realized that I rebased on the master before the other PR was merged, but should be the latest master now.

> Thanks for stepping up to work on these PRs anyways :)

And thanks for your work on this plugin (even when I don't use it anymore). 👍

**Comment by samrocketman** [comment]
> And thanks for your work on this plugin (even when I don't use it anymore).

Thanks, I don't use it either which is why I stepped away from it.  But the open PRs are a bit itchy for me.  Do you still use Jenkins?

**Comment by SuperTux88** [comment]
> Do you still use Jenkins?

Yes (private and for work).

**Comment by samrocketman** [comment]
As thanks for your work, allow me to point out some scripts you may find useful.

* [`say_job_done.sh`](https://github.com/samrocketman/home/blob/master/bin/say_job_done.sh) - works on Linux or Mac.  Screams at you to audibly tell you something on the command line is done.  Useful for not having to check your terminal for things to finish.
* [`provision_jenkins.sh`](https://github.com/samrocketman/home/blob/master/bin/provision_jenkins.sh) - Provision Jenkins in a quick sandbox to test personal configurations.  Meant to be run on Linux or Mac.
* [`job-wait`](https://github.com/samrocketman/home/blob/master/bin/job-wait) - Waits for a Jenkins job to finish.  If a job is in progress then the script will periodically wait until the Jenkins job completes.  If the job is anything but success then it will exit with a non-zero exit status.

Some example usage (assuming the scripts are in your `$PATH`):

```bash
#if on Linux install the espeak package
say_job_done.sh

#provision Jenkins (login information will be printed at the end of bootstrap)
provision_jenkins.sh bootstrap

#use job-wait to wait for a Jenkins job and then be audibly alerted
export JENKINS_WEB=https://jenkins.ci.cloudbees.com
job-wait -d https://jenkins.ci.cloudbees.com/job/plugins/job/slack-plugin/382/ ; say_job_done.sh
```

Here's some example output from `job-wait`.

```
$ export JENKINS_WEB=https://jenkins.ci.cloudbees.com
$ job-wait -d https://jenkins.ci.cloudbees.com/job/plugins/job/slack-plugin/382/
Detect CSRF protection.
CSRF protection enabled.
Checking build https://jenkins.ci.cloudbees.com/job/plugins/job/slack-plugin/382
Duration: 4 minutes 16 seconds
SUCCESS
$ echo $?
0
```

Finally, [here's a video](https://www.youtube.com/watch?v=T1x2kCGRY1w) in which I got positive feedback on.  You may find it useful.

Thanks again.

**Comment by SuperTux88** [comment]
Thanks :D

**Comment by samrocketman** [comment]
Tested with https://github.com/samrocketman/jenkins-bootstrap-slack .  It works for me.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.

**Comment by xenjke** [comment]
Do you guys have any luck got test failures being attached to a slack post after the 2.2 release? No luck for me, Jenkins is able to display the test report but slack post is just "build failed after 20sec". Any advice?

**Comment by samrocketman** [comment]
I tested this the best I could.  Feel free to open an issue and @ mention the original author.

**Pull request merged**
