### PR TITLE
Fix #188 Fixes for configuration migration from 1.8 to 2.0

### LINKED ISSUE #188: FATAL: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor since 2.0
Since the upgrade to 2.0 we have the following error for all our builds:

```
FATAL: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
    at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1223)
    at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
    at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
    at hudson.model.Descriptor.toMap(Descriptor.java:973)
    at hudson.model.Job.getProperties(Job.java:558)
    at hudson.model.Build$BuildExecution.post2(Build.java:187)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

Downgrade to 1.8.1 seems to solve the issue.
Jenkins version: 1.652
# See possible fix

edit by @samrocketman: See #191 for possible fixes for this issue.

### PR DESCRIPTION
**Pull request by OwensCode**
Migrate multi-branch-project plugin template configuration from 1.8
format to 2.0 format.

### CODE REVIEW

**Comment by OwensCode** [comment]
I've added more changes to fix issues with pipeline jobs, and I also refactored the configuration migration code quite extensively because it was becoming more complicated. It's all in this PR because nobody seemed to be reviewing it yet, and the changes are all related.

**Comment by froland** [comment]
Hi. Just sharing some feedback. I've encountered the same stacktrace running jobs that were created with Job DSL and seed plugins. I built the slack plugin from this pull request and now it runs OK.

**Comment by OwensCode** [comment]
Thanks @froland!

**Comment by samrocketman** [comment]
> I built the slack plugin from this pull request and now it runs OK.

Nice!  I'll let @kmadel weigh in for the final merge.

**Comment by froland** [comment]
Sorry, I was a bit too quick at celebrating. When I updated the plugin, the jobs already created worked but not the one I tried to build through the seed plugin afterwards. Weird. I'll investigate a bit more if I get some time.

**Comment by OwensCode** [comment]
@froland I don't think anyone has mentioned the seeds plugin yet; I'll have to take a closer look. Let me know if you dig up any more details.

**Comment by OwensCode** [comment]
@froland If I'm understanding what you're saying correctly, this issue needs to be fixed within the job dsl plugin (although it is caused by the slack plugin configuration change); it needs to be updated to generate the latest slack plugin configuration. Take a look at https://issues.jenkins-ci.org/browse/JENKINS-34124. If you scroll down to the bottom of that issue, there may have been a recent release that rectifies the situation.

If I'm not understanding you correctly, could you please post your seed configuration (or relevant parts of it) so I can test with it. Thanks.

**Comment by froland** [comment]
@OwensCode, your last comment is right. I'm still getting the following stack trace after updating all my Jenkins plugins to their latest version, but I guess this issue is more on the Job DSL plugin side.

FATAL: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
java.lang.AssertionError: class jenkins.plugins.slack.SlackNotifier$SlackJobProperty is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1225)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:105)
	at hudson.model.JobProperty.getDescriptor(JobProperty.java:79)
	at hudson.model.Descriptor.toMap(Descriptor.java:973)
	at hudson.model.Job.getProperties(Job.java:558)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by dalvizu** [comment]
I just used this to test out the fix for #188 -- works for me!

@samrocketman @kmadel I don't believe there were any issues in this pull request - the discussion above is about job-dsl, but it is orthogonal to this change. Can this be merged?

**Comment by kmadel** [comment]
Please merge the latest changes from master into this branch.

**Comment by OwensCode** [comment]
@kmadel I've merged master into this branch.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.

**Pull request merged**
