### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Enables CI for the plugin

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Most likely it will fail. The plugin uses ancient parent POM

**Comment by oleg-nenashev** [comment]
@kmadel

**Comment by omegas27** [comment]
The code is merged but i can't install the plugin to use Configuration-as-code. How can i do that ? Specify the artifact url directly from https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/master/10/artifact/target/slack.hpi ?

**Comment by timja** [comment]
in advanced you can upload from a local file,
so download the hpi file from the link go to advanced in plugin centre and upload it there
and restart jenkins if you had an older version installed

**Comment by omegas27** [comment]
Thanks for your input. I added that in my docker image. When is the plugin gonna be released ? Last release was more than a year ago (august 2017)

**Comment by timja** [comment]
Pending this PR I think:
https://github.com/jenkinsci/slack-plugin/pull/406

Maybe more, @kmadel ?

**Pull request merged**
