### PR TITLE
resolve #232 use DataBoundSetter for optional params

### LINKED ISSUE #232: add defaults for slackNotifier job DSL api
We are using the job dsl to describe our jobs. The `slackNotifications` method is deprecated in favor of the new `slackNotifier` method that comes from the extension points.

The old `slackNotifications` provided many defaults so we could configure e.g. the slackDomain, token, etc. globally in jenkins and then only add a small block like 

```
    publishers {
        slackNotifications {
            projectChannel('channel')
            notifyUnstable()
            notifyFailure()
            notifyBackToNormal()
        }
    }
```

but with the new `slackNotifier` method we have to specify all the properties:

```
ERROR: the following options are required and must be specified: teamDomain, authToken, buildServerUrl, sendAs, startNotification, notifyAborted, notifyNotBuilt, notifySuccess, notifyRepeatedFailure, includeTestSummary, commitInfoChoice, includeCustomMessage, customMessage
```

Is it possible to add defaults with extension points?

### PR DESCRIPTION
**Pull request by sheehan**
Modify SlackNotifier to use `DataBoundSetter` instead of constructor params. This resolves #232.

See also https://groups.google.com/forum/#!topic/job-dsl-plugin/JWO7zDuMYVA

### CODE REVIEW

**Comment by samrocketman** [comment]
Seems like a relatively straight forward change.  I'll leave this open for review for others to comment.

**Comment by zafarella** [comment]
pls merge

**Comment by daspilker** [comment]
@kmadel can you merge this please? I want to drop the built-in support for the Slack plugin in the next release of the Job DSL plugin. Without `@DataBoundSetter`, the DSL needs to consider all options as mandatory. This would be a major setback for DSL users as the need to inflate their script by adding many options with their default vault.

**Comment by daspilker** [comment]
@sheehan can you ask on the Jenkins dev list for commit access to this repo to get this merged?

**Comment by MichaelPereira** [comment]
This change would be welcome, please consider asking for review or commit access to https://groups.google.com/forum/#!forum/jenkinsci-dev @sheehan, thanks ! 😄

**Comment by kmadel** [comment]
I will be happy to merge once the conflict is resolved and there are two thumbs up for a code review.

**Comment by sheehan** [comment]
rebased

**Comment by daspilker** [comment]
look good 👍

**Comment by fgs-dbudwin** [comment]
Any progress on this?  Looks a like another rebase is in order @sheehan

**Comment by sheehan** [comment]
up to date

**Comment by samrocketman** [comment]
I'll review this next week and merge it if nothing is done by then.  Currently, other life events have my attn this week.

**Comment by samrocketman** [comment]
I just upgraded my automated scripts for bootstrapping Jenkins configured with slack.  https://github.com/samrocketman/jenkins-bootstrap-slack  I'm going to test this today and if all checks out I'll merge it.

**Comment by samrocketman** [comment]
Tested and works just fine.

**Comment by daspilker** [comment]
Thanks for merging this. Are you planning to cut a release anytime soon?

**Comment by samrocketman** [comment]
Yeah, I'm trying to get a few more PRs rebased/merge.  However, I'm willing to commit to a release by this coming weekend.

**Comment by Daniel15** [comment]
Thanks for this pull request. I'm not using the Slack plugin, but this helped me understand the exact same issue with another plugin.

@daspilker - Is the fact that plugins should use `DataBoundSetter`s for Job DSL documented anywhere?

**Comment by daspilker** [comment]
@Daniel15 use `DataBoundConstructor` for mandatory settings and `DataBoundSetter` for optional settings.

**Comment by Daniel15** [comment]
Sure, I understand that now, but is it mentioned in documentation anywhere (either Jenkins docs or Job DSL docs)? 😃

**Comment by Daniel15** [comment]
@daspilker - Sure, I understand that now, but is it mentioned in documentation anywhere (either Jenkins docs or Job DSL docs)? 😃

**Comment by samrocketman** [comment]
@daspilker feel free to subscribe to https://github.com/jenkinsci/slack-plugin/issues/296 for release updates.

**Pull request merged**
