### PR TITLE
Don't use saved global params when testing globally

### PR DESCRIPTION
**Pull request by timja**
Ignores saved configuration, only uses configuration currently in the form

See https://github.com/jenkinsci/slack-plugin/issues/728#issuecomment-689022347

### CODE REVIEW

**Review by jetersen — APPROVED** [review]

**Comment by timja** [comment]
Hmm @XiongKezhi I just clicked re-run from this PR's failure and it rebuilt the master build =/

Wrong SCMHead retrieved?

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fslack-plugin/detail/master/276/pipeline

image

https://github.com/jenkinsci/slack-plugin/pull/729/checks

**Comment by XiongKezhi** [comment]
it will only re-run the master when there is no PR information included in the request payload: https://github.com/jenkinsci/github-checks-plugin/blob/8811725f694e2f87cf77a986e7428ac31df93db1/src/main/java/io/jenkins/plugins/checks/github/CheckRunGHEventSubscriber.java#L111.

**Comment by XiongKezhi** [comment]
did you rerun the checks after you merged or before? I tried on a merged PR (https://github.com/jenkinsci/github-checks-plugin/pull/47/checks?check_run_id=1079933661) just, reproduced it. I'll check whether this is the reason.

**Comment by timja** [comment]
@XiongKezhi before I merged

**Pull request merged**
