### PR TITLE
add baseUrl parameter to support slack-compatible integrations

### PR DESCRIPTION
**Pull request by Reamer**
- Remove Merge Conflicts from https://github.com/jenkinsci/slack-plugin/pull/204
- Add some documentation

### CODE REVIEW

**Comment by samrocketman** [comment]
@Reamer can you ammend your PR so that there's two commits?  One commit for the author of #204 and a second commit for your additional changes?  I prefer to preserve credit where due in the contributor statistics.  If you like; give me write access to your branch and I can do it for you.

**Comment by samrocketman** [comment]
I'll test this change now.

**Comment by samrocketman** [comment]
So far in my testing; upgrading the plugin from 2.1 to 2.2-SNAPSHOT doesn't break any configurations.  That's a good start.  Now I'm going to review the code.

**Comment by samrocketman** [comment]
I have mattermost configured on `http://localhost:8065/`.  How do I configure the Slack plugin to interact with it?  I don't know how to test this feature.

Bootstrap Jenkins with slack configured and a mattermost machine (requires vagrant).

1. Clone https://github.com/samrocketman/jenkins-bootstrap-slack
2. Bring up mattermost; `vagrant up`; once mattermost is up you can visit `http://localhost:8065/`.
3. Bring up Jenkins; `./slack_bootstrap.sh`; The end of the console output will include how to log into it.

Beyond that; I don't know how to test the integration.

**Comment by Reamer** [comment]
@samrocketman You have now write access to my branch.
To test this feature with mattermost:
1. Login to Mattermost
2. click in the upper right corner on three points
3. click on Integrations
4. click on Incoming Webhooks
5. Create a Webhook
6. You should now have a URL with a Token, something like this (https://mydomain.com/hooks/xxxxxxxxxxxxxx)
7. "https://mydomain.com/hooks/" is your baseUrl + "xxxxxxxxxxxxxx" your token.

Now I will take a look into your Vagrant-Box

**Comment by Reamer** [comment]
@samrocketman: Vagrant is up and running, but I doesn't want a local jenkins server on my os. I was wondering that the integration button was missing. After a clean install you must enable this integration 
Go to http://localhost:8065/admin_console/integrations/custom and enable webhook integration. After this you can follow my instructions in my last comment.

Let me know ,if I can help you with testing.

**Comment by samrocketman** [comment]
Thanks, I'll try it tomorrow.

**Comment by samrocketman** [comment]
# Testing

So far adding a trailing slash is required.  I configured Base URL = `http://localhost:8065/hooks/` and "Test Connection" button succeeded.  However, Base URL = `http://localhost:8065/hooks` causes "Test Connection" button to fail.  It should not matter; this is a bug.

**Comment by samrocketman** [comment]
# Fully Tested

Okay, this has FINALLY been successfully tested.  I tested the following:

1. Upgrading configurations from prior version of Slack plugin (success).
2. Configured with Mattermost using `http://localhost:8065/hooks` (no trailing slash) (success).
3. Configured with Mattermost using `http://localhost:8065/hooks/` (trailing slash) (success).

This pull request is ready to be merged!

**Comment by samrocketman** [comment]
Thanks for your work @Reamer and @andrzejwp.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.

**Comment by andrzejwp** [comment]
Great! Sorry I didn't asist further. Hope this makes it to the public release soon. Thanks!

**Comment by samrocketman** [comment]
No worries.  It's challenging to stay on top of volunteer stuff so I appreciate your contributions.

**Pull request merged**
