### PR TITLE
Option To Post Test results On Slack

### PR DESCRIPTION
**Pull request by akhilojha**
Added option in job configuration to post test results on slack.
Total, Passed, failed, skipped Test results.

### CODE REVIEW

**Comment by crrobinson14** [comment]
Is this going to be merged? This looks super helpful. Thanks @akhilojha for putting it together!

**Comment by samrocketman** [comment]
I guess I'll start maintaining this plugin.  I don't have any experience developing Jenkins plugins but if I can get my own environment set up and learn to release then I'll do it.  This may take about a week.

**Comment by samrocketman** [comment]
This seems to duplicate #25.  I think it's a little cleaner and concise for the test summary to be all on one line.  I'll likely merge #25 but I'll certainly test out your change to be sure in a local build.

**Comment by samrocketman** [comment]
pr25_vs_pr33

Above is the results of the tests between pull requests #25 and #33.  (`trogdor` is #25 and `the_burninator` is #33).  I think #25 is a little cleaner in how the output is formed so I'm going to accept that instead.  I'll be closing this PR unmerged.

**Comment by crrobinson14** [comment]
@samrocketman Thanks for picking up the lead on this! I personally preferred this one but it's super-subjective, and it's really great just to move it forward. Appreciate your contribution!

**Comment by akhilojha** [comment]
@samrocketman Thanks for looking into it and merging the appropriate request.
@crrobinson14 I preferred this one too :)

**Comment by samrocketman** [comment]
@akhilojha yeah, it was a toss up mostly.  Both of them gave the same thing.  Hopefully, you're not discouraged from future contributions.  Thanks for opening this PR.

**Pull request closed without merging**
