### PR TITLE
Thread support

### PR DESCRIPTION
**Pull request by iulianstana**
Current implementation adds support for slack threading.

Currently, slack supports thread notification using "chat.postMessage".
In order to use threads a bot user with the support of "chat.postMessage"
need to be used.

Slack hooks currently don't have a thread support.

### CODE REVIEW

**Comment by kmadel** [comment]
@steven-foster I will take a look this weekend. In the meantime, would you be able to do a review?

**Comment by iulianstana** [comment]
I've managed to modify my `slack bot commands` and `jenkins jobs` to use thread support and we are extremely happy with the result.

I would be happy to help merging this in master :)

slack_threads

**Comment by steven-foster** [comment]
Sorry I didn't see your message @kmadel. I'm not a Java developer really, nor very familiar with the codebase of this plugin so I'm not totally sure about the implementation of this feature. It seems fine, and it works.
I noticed that the description for `bot user` and the slack docs seem like they contradict each other.
>Pass true to post the message as the authed user, instead of as a bot. 

but it seems to work anyway?

Also, a big improvement to this feature would be a full-flow example of posting a message and adding thread replies to it. Currently I have trouble with finding the correct thread_ts.

**Comment by iulianstana** [comment]
Hello @steven-foster, us use `Hubot` robot. 
I would need some help from you to write the correct documentation. Probably I will miss some steps...

Steps:
1) Each Slack message that is received in `hubot` app has a special `object` (msg)
2) When a new message is received from a channel a timestamp is set on `msg.message.rawMessage.ts` (Slack message timestamp).
3) To make `hubot` respond in a thread you should set `msg.message.thread_ts = msg.message.rawMessage.ts`.
     From this moment all messages that will be written using `msg` object will be written under `msg.message.rawMessage.ts`
Obs: if you communicate with your `hubot` in a thread `msg.message.thread_ts` will already be set on 
`msg.message.rawMessage.ts`

Jenkins side
1) I've added a new param to all of my `buildflows` (named `slack_room`). This parameter is filled by `hubot` with a slack room and a thread_ts (`msg.message.room + ":" + msg.message.thread_ts`)
2) I've created a new secret key to be used ( `jenkins-key` from slack app, it's a new `hubot` app token created in slack) (👎 `jenkins-slack` token will not work)
3) Then, in my `buildflows` I've checked `botUser`, I've used my created `jenkins-key` and fill up the `room` with $slack_room (`room:thread_ts`)

I will help you merge this feature as fast as you wish.

**Comment by steven-foster** [comment]
Hi @iulianstana, thanks for the explanation. I was doing something similar but not with hubot. I got some feedback from people who just wanted to add threads to the messages they sent with the slack plugin, so that's why I was curious about your workflow.

I made a PR for your repo (this PR) which returns a response object from the pipeline step with all the info needed to send a thread. My java isn't too strong, so let me know if it's a good approach.

**Comment by iulianstana** [comment]
@kmadel Resolved conflict with master. Would you like from me to add some additional documentation?

**Comment by iulianstana** [comment]
@kmadel Can I help you with this PR?

**Pull request merged**
