### PR TITLE
fix test summary / notify repeated failure config

### PR DESCRIPTION
**Pull request by graphaelli**

### CODE REVIEW

**Comment by samrocketman** [comment]
I've peer reviewed it and compared it to lines 214-226 of that same file.  I think I understand the bug you're fixing.  Thanks for catching that.  I'll build the plugin and ensure that the fix works.  Upon successful testing I'll merge your request.

**Comment by samrocketman** [comment]
I have verified this bug in the 1.7 release.

**Comment by graphaelli** [comment]
Thanks for deciphering my cryptic report.  The issue this addresses is the mismatch between the checkboxes in the `Advanced` section of the Slack notification configuration.  The `Notify Repeated Failure` was being passed into the constructor on https://github.com/graphaelli/slack-plugin/blob/checkboxes/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L224-L225 for `Include Test Summary`

**Comment by samrocketman** [comment]
Yeah, I saw that.  I believe I encountered this bug during testing and almost realized it.  I had checked the boxes for including test summary and noticed the tests weren't passing.  Then I went back and saw that it wasn't checked.  I thought, at the time, I had simply clicked the wrong box.

Good catch.

**Pull request merged**
