### PR TITLE
Force jenkins-ci hook when base url mis-configured

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by rodrigc** [comment]
I tried this plugin with my setup.  I managed to successfully *Test Connection*.
And saw the notification go through to the slack channel which I set up.

I got this warning every time I clicked on *Test Connection*:

```
WARNING: Overriding base url to team domain 'portworx' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost
```

If I removed the override url, and just used the team domain, then I got:

```
Failure: {"ok":false,"error":"invalid_auth"}
```

So for my setup, I need the override URL, otherwise it doesn't work.

Is this warning going to print every time slack sends something?  I'll get hundreds of warnings in my log.

**Comment by casz** [comment]
@rodrigc have you tried creating a new token?

**Comment by timja** [comment]
> I tried this plugin with my setup. I managed to successfully _Test Connection_.
> And saw the notification go through to the slack channel which I set up.
> 
> I got this warning every time I clicked on _Test Connection_:
> 
> ```
> WARNING: Overriding base url to team domain 'portworx' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost
> ```
> 
> If I removed the override url, and just used the team domain, then I got:
> 
> ```
> Failure: {"ok":false,"error":"invalid_auth"}
> ```
> 
> So for my setup, I need the override URL, otherwise it doesn't work.
> 
> Is this warning going to print every time slack sends something? I'll get hundreds of warnings in my log.

Can you add the log message that slackSend logs without this PR?
I'm wondering if someone is setting botUser somewhere

**Comment by rodrigc** [comment]
Without this patch, I have hundreds of logs like this from `slackSend()`:

https://github.com/jenkinsci/slack-plugin/issues/594#issuecomment-516740921

**Comment by basil** [comment]
FYI, when upgrading from version 2.11 to version 2.33 with this PR I started getting the following error when running the `slackSend` step:

```
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at jenkins.plugins.slack.StandardSlackService.correctMisconfigurationOfBaseUrl(StandardSlackService.java:134)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:193)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:292)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:287)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:342)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:248)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by rodrigc** [comment]
@basil can you post details of the slack portion of your Jenkins setup?  (Comment out any sensitive data), similar to what I did here: https://github.com/jenkinsci/slack-plugin/issues/594#issuecomment-516948297

**Comment by basil** [comment]
> @basil can you post details of the slack portion of your Jenkins setup? (Comment out any sensitive data), similar to what I did here: [#594 (comment)](https://github.com/jenkinsci/slack-plugin/issues/594#issuecomment-516948297)

The Slack portion of my Jenkins setup is completely blank; I don't have any global configuration. I just configure each `slackSend` step individually.

**Comment by timja** [comment]
Fixed released in 2.34 sorry about that @basil 
https://github.com/jenkinsci/slack-plugin/releases/tag/slack-2.34

**Comment by basil** [comment]
Thank you!

**Comment by rodrigc** [comment]
@timja This fix helps a bit, but I'm still getting hundreds of warnings in the Jenkins log:

```
Sep 30, 2019 6:54:46 AM jenkins.plugins.slack.StandardSlackService correctMisconfigurationOfBaseUrl
WARNING: Overriding base url to team domain 'XXXX' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost`
```

*CONFIGURATION 1: Set the Workspace, leave the override URL empty*

If I set the team domain, auth fails completely if I click on *Test Connection*.

Screen Shot 2019-09-30 at 6 52 16 AM

*CONFIGURATION 2: Unset the Workspace, populate the override URL, select bot user*

Auth succeeds but I get a warning in the log:
```
Sep 30, 2019 6:54:46 AM jenkins.plugins.slack.StandardSlackService correctMisconfigurationOfBaseUrl
WARNING: Overriding base url to team domain 'XXX' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost
```

Screen Shot 2019-09-30 at 6 53 12 AM

*CONFIGURATION 3: Unset the Workspace, populate the override URL, unselect bot user

Auth succeeds but I get a warning in the log:
```
Sep 30, 2019 7:11:38 AM jenkins.plugins.slack.StandardSlackService correctMisconfigurationOfBaseUrl
WARNING: Overriding base url to team domain 'XXX' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost
```
Screen Shot 2019-09-30 at 6 56 21 AM


Is there a way that the slack-plugin can stop printing out this warning, since I
cannot get this to work unless I use the override URL.  I got the override URL by
creating a new integration at https://XXX.slack.com/services/new/jenkins-ci

**Comment by rodrigc** [comment]
Ah OK, that worked, thanks.  From the instructions, and the error message, this is not obvious.

**Comment by timja** [comment]
Could you suggest where it could be improved or even better a pull request to docs or UI?

**Comment by rodrigc** [comment]
@timja I can confirm that the latest plugin works.

To minimize user error, I would recommend that the UI be changed so that if
someone enters in the **Override url** field any string which matches **slack.com/services/hooks/jenkins-ci**, then the UI should print out a warning or error message in red.

This was not obvious to me when I set this up originally, and having the UI provide more useful hints would have been helpful

**Comment by timja** [comment]
Created https://github.com/jenkinsci/slack-plugin/issues/635

**Pull request merged**
