### PR TITLE
Enable use system properties on http client - fixes tls 1.2 issues in some cases

### LINKED ISSUE #673: SSLHandshakeException while posting to slack
### Data
Jenkins version: 2.202
Plugin version: 2.37
OS: Linux

### Description

Jenkins is unable to send notifications to slack due to following exception:

image

I tried to post message to my slack url via postman and it worked correctly.

### PR DESCRIPTION
**Pull request by Jetersen**
partial fix of #673

### CODE REVIEW

**Comment by Jetersen** [comment]
if `useSystemProperties` is not called it goes into 

https://github.com/apache/httpcomponents-core/blob/49da50b1b2947f8b9613b9f691743a5fb6228eda/httpcore/src/main/java/org/apache/http/ssl/SSLContexts.java#L49-L53

switch uses TLS 1.0 only

see: https://github.com/apache/httpcomponents-client/blob/c87a3488c45493c165c886bcd8b63b3724a1e2cc/httpclient/src/main/java/org/apache/http/impl/client/HttpClientBuilder.java#L957-L982

**Comment by Jetersen** [comment]
Hmm not sure it fixes it, I wrote a test using the endpoint: `https://slack.com/api/api.test` and it passes just fine with our without this test on my machine. I guess it highly depends on java version still.

**Comment by Jetersen** [comment]
Hmm not seeing a handshake failure 🤔

**Comment by timja** [comment]
I tested our prod instance on Linux Jdk 8 and it has no issues 
Very OS and java vendor specifics I would assume the problem is

**Comment by Jetersen** [comment]
PR is blocked until someone with the problem is willing to test the `hpi`.

**Comment by Jetersen** [comment]
Oh I know...

Slack uses a new certificate that is not included in their root ca...

**Comment by Jetersen** [comment]
Does not fix issue

**Pull request merged**
