### PR TITLE
Remove  slack outgoing webhook functionality

### LINKED ISSUE #283: Slack Webhook get 403 status code if jenkins disable anonymous access
I recent enable slack plugin and try to use webhook function, but it not works. Checking the access log, it shows the access was rejected by Jenkins with 403 status code.

By looking into Jenkins core source code, it shows the current `WebhookEndpoint.java` return "getUrlName()" with "/" prefix, but most `UnprotectedRootAction` implementation just use single word without "/" prefix.

The following are the detailed information that I found, and hope this can help you can find root cause. Thanks.

**1. Example for 403 error (use "webhook" as endpoint):**
```
[06/Feb/2017:16:53:57 +0000] "POST /webhook/ HTTP/1.1" 403 813 "-" "Slackbot 1.0 (+https://api.slack.com/robots)" "-" "-" 0.026
```

Use browser to verify this and find if login success, it works (405 status here because use "GET" not expected "POST"):
```
[06/Feb/2017:17:20:49 +0000] "GET /webhook/ HTTP/1.1" 403 813 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" "-" "-" 0.004
[06/Feb/2017:17:20:56 +0000] "GET /webhook/ HTTP/1.1" 405 217 "http://xxxx/login?from=%2Fwebhook%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36" "-" "-" 0.006
```

**2. Validate `getUnprotectedRootActions` result**
Inspect `Jenkins.getInstance().getUnprotectedRootActions()` in jenkins script console, it shows all other unprotected urls are simple words, except slack webhook.

```
Result: [/webhook, assets, cli, git, github-webhook, instance-identity, jnlpJars, project, subversion, whoAmI]
```

**3. The possible code invoking `getUrlName()` in Jenkins core has special logic to check URL.**
The jenkins core source code for function `isSubjectToMandatoryReadPermissionCheck()` has special logic to validate if any incoming URL can anonymous access:
```java
        for (String name : getUnprotectedRootActions()) {
            if (restOfPath.startsWith("/" + name + "/") || restOfPath.equals("/" + name)) {
                return false;
            }
        }
```
See https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L4575-L4595

If `name` variable has "/" prefix for slack webhook, then all un-protected-root-actions will not match and fail into protected logic.

**4. The original source for slack-plugin has no "/"**
Checking https://github.com/dpires/jenkins-slack-webhook-plugin/blob/master/src/main/java/org/jenkinsci/plugins/slackwebhook/WebhookEndpoint.java#L59-L61 find "webhook" is simple returned in the method.

Based on those static code review and investigation, I am thinking the `getUrlName()` in WebhookEndpoint.java should not add prefix "/". Although this is functional for endpoint, but may break if security is enabled and disable anonymous access. If this can be checked and verified, that will be helpful for us to enable command from slack to Jenkins server.

### PR DESCRIPTION
**Pull request by timja**
They're deprecated and I don't believe anyone is using this feature:
https://api.slack.com/custom-integrations/outgoing-webhooks

Fixes https://github.com/jenkinsci/slack-plugin/issues/281
Fixes #283

See https://github.com/jenkinsci/slack-plugin/pull/160#issuecomment-215839006

If anyone is using this feature and would like it restored, raise an issue about it and we can discuss either restoring it or adding the required feature for the slack app functionality

### CODE REVIEW

**Comment by mecorusfc** [comment]
What does this mean?  Does this mean that I can't have a job notify Slack any more?  If so, we need this feature.

**Comment by timja** [comment]
No it doesn’t mean that

It means the feature that allowed you to send messages in slack to trigger jobs etc has been removed.

(It was never documented and didn’t work when authentication was required and had some other quirks)

**Comment by JamesXNelson** [comment]
so, is there any other way of creating a slack bot?  we were recently discussing doing this at one of my clients.

**Comment by timja** [comment]
not currently implemented in this plugin, but you would probably use slash commands in a slack app

**Comment by casz** [comment]
@JamesXNelson plenty of ways.

depends what you need?

Options include:

Frameworks:
Use Slack's own framework Bolt (javascript): https://slack.dev/bolt/concepts
Use Botkit (javascript): https://botkit.ai allows you to bots for most chat platforms
Use Microsoft Botframework (c#, javascript): https://www.botframework.com

Otherwise there are plenty of libraries:
https://api.slack.com/community

We use a older version of Botkit but it still works just fine :)
Though for our current needs we properly want to switch to Microsoft BotFramework and develop using C#

**Pull request merged**
