### PR TITLE
Rebase and resolve original PR #156 to fix issue #102 from nevermindr 

### PR DESCRIPTION
**Pull request by jiamengyu**
Resolved the conflicts and tested the proxy issue.

### CODE REVIEW

**Comment by samrocketman** [comment]
Please squash your commits into a single commit.  Once you do that, I'll review and do some testing of my own.

**Comment by samrocketman** [comment]
Also, ensure your squashed commit is rebased on the latest master.

**Comment by jimsonyu** [comment]
@samrocketman  Have invited you to my reposiroty and given write access.   Please squash as needed. Thank you a lot for helping.

**Comment by jiamengyu** [comment]
Done with squashing into single commit.

**Comment by samrocketman** [comment]
@jiamengyu I'm going to update your commit authorship to attribute @nevermindr.  I'll test this evening.

**Comment by samrocketman** [comment]
@jiamengyu I have rebased and tried to retain the authorship from both #156 and this PR.  Please approve.  cc @nevermindr

**Comment by jiamengyu** [comment]
Where can I approve?  is there a button? or what action need to be done for approval?

**Comment by samrocketman** [comment]
@jiamengyu I just wanted you to see what I did and approve with a simple comment.  I wanted to be sure I wasn't doing something you didn't like.

**Comment by jiamengyu** [comment]
@samrocketman I've reviewed all the changes one more time, looks all good! Please proceed with merging if all testing passed.
Great thanks.

**Comment by caleyg** [comment]
double posting from #148 to try and get a response from a party who is watching...

Can anyone please give me some insight here. I'm trying to use this plugin in my Jenkins Pipeline build behind a proxy in an enterprise environment.

slackSend isn't honoring http_proxy, https_proxy, or HTTP_PROXY, HTTPS_PROXY or -Dhttp.proxyHost or -Dhttps.proxyHost.

I know Jenkins use the proxy by leveraging one of the environment variables above, because I'm able to do things like install plugins from the plugin manager, and use the proxy in various other build tasks.

But consistently the slack plugin just times out when connecting to slack.com

I'm very close to pivoting and leveraging curl to send my requests... I've tried this with slack plugin 2.2 and slack 2.3

**Comment by jimsonyu** [comment]
Hey,it is not using any of the http_proxy env . you should configure the proxy information on Jenkins itself.Let  me find out the navigation path for you when I get  back to my computer.Jim                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device - via the Bell Network                                                                                                                                                                            From: notifications@github.comSent: October 19, 2017 6:05 PMTo: slack-plugin@noreply.github.comReply-to: reply@reply.github.comCc: jim@itmercenaries.ca; comment@noreply.github.comSubject: Re: [jenkinsci/slack-plugin] Rebase and resolve original PR #156 to fix issue #102 from nevermindr (#299)  double posting from #148 to try and get a response from a party who is watching...
Can anyone please give me some insight here. I'm trying to use this plugin in my Jenkins Pipeline build behind a proxy in an enterprise environment.
slackSend isn't honoring http_proxy, https_proxy, or HTTP_PROXY, HTTPS_PROXY or -Dhttp.proxyHost or -Dhttps.proxyHost.
I know Jenkins use the proxy by leveraging one of the environment variables above, because I'm able to do things like install plugins from the plugin manager, and use the proxy in various other build tasks.
But consistently the slack plugin just times out when connecting to slack.com
I'm very close to pivoting and leveraging curl to send my requests... I've tried this with slack plugin 2.2 and slack 2.3

**Comment by jiamengyu** [comment]
@caleyg  Login to your jenkins instance, go to "Manage Jenkins", then click "Manage plugins", then click Tab: advanced, then fill your "HTTP Proxy Configuration".
Your SlackSend should be working as expected behind enterprise proxy.

**Comment by caleyg** [comment]
Thank you :)

**Pull request merged**
