### PR TITLE
add custom message for manually triggered builds on build start

### PR DESCRIPTION
**Pull request by MilesRoberts**
fixes a bug introduced in #137 that dropped custom message from the slack notification if the build wasn't kicked off by an SCM change

I tested locally and it's a pretty small change, but it could probably stand a second shakedown.

### CODE REVIEW

**Comment by kmadel** [comment]
@MilesRoberts Please fix merge conflict(s).

**Comment by samrocketman** [comment]
Please rebase this on the latest master.

**Comment by samrocketman** [comment]
I plan on performing a release this weekend. If you would like this PR to be in it then please rebase/resolve.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.

**Pull request merged**
