### PR TITLE
102 - Slack notification plugin error proxy

### PR DESCRIPTION
**Pull request by nevermindr**
Fix for HTTP Proxy:
rewritten POST to Slack with httpclient4.3.2

### CODE REVIEW

**Comment by nevermindr** [comment]
closing, tests not fixed

**Comment by samrocketman** [comment]
FYI, You don't need to close and re-open pull requests.  By updating the branch you update the pull request (including force pushing to overwrite history in the pull request).

**Comment by nevermindr** [comment]
I'll keep this in mind. Sorry for a little mess :)

**Comment by samrocketman** [comment]
No worries it didn't bother me.  Just letting you know for your own benefit (a little less work that way).

**Pull request closed without merging**
